apiVersion: v2
name: yourss
type: application
version: 0.9.3
appVersion: 0.9.3
description: Simple Youtube browser based on RSS feeds
home: https://github.com/essembeh/YouRSS
maintainers:
  - email: essembeh@users.noreply.github.com
    name: Sébastien MB
sources:
  - https://github.com/essembeh/YouRSS
