apiVersion: v2
name: yourss
type: application
version: 0.7.2
appVersion: 0.7.2
description: Webapp to subscribe to Youtube channels using RSS
home: https://github.com/essembeh/YouRSS
maintainers:
  - email: essembeh@users.noreply.github.com
    name: Sébastien MB
sources:
  - https://github.com/essembeh/YouRSS
