[tool.poetry]
name = "yourss"
version = "0.2.0"
description = "Simple youtube browser based on RSS feeds"
homepage = "https://github.com/essembeh/yourss"
authors = ["Sébastien MB <seb@essembeh.org>"]
license = "Apache-2.0"
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Utilities"
]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.7"
importlib_metadata = { version = "", python = "< 3.8" }
requests = ""
lxml = ""
cached-property = ""
SQLAlchemy = ""
Flask = ""
Flask-SQLAlchemy = ""
Flask-RESTful = ""
Flask-JWT-Extended = ""
Flask-Login = "^0.5.0"
beautifulsoup4 = "^4.9.3"


[tool.poetry.dev-dependencies]
black = ""
pylint = ""
pytest = ""
pytest-dotenv = ""
pytest-cov = ""


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
