[tool.poetry]
name = "yourss"
version = "0.7.1"
description = "Simple youtube browser based on RSS feeds"
homepage = "https://github.com/essembeh/yourss"
authors = ["Sébastien MB <seb@essembeh.org>"]
license = "Apache-2.0"
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Utilities"
]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.109.0"
beautifulsoup4 = "^4.12.2"
jinja2 = "^3.1.2"
arrow = "^1.2.3"
loguru = "^0.7.2"
environ-config = "^23.2.0"
redis = "^5.0.1"
httpx = "^0.26.0"


[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
pylint = "^3.0.3"
pytest = "^7.4.1"
pytest-cov = "^4.1.0"
pytest-dotenv = "^0.5.2"
uvicorn = "^0.25.0"
isort = "^5.12.0"
types-redis = "^4.6.0.20240106"
pytest-asyncio = "^0.21.1"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
