[tool.poetry]
name = "yourss"
version = "0.12.0"
description = "Simple Youtube browser based on RSS feeds"
homepage = "https://github.com/essembeh/yourss"
authors = ["Sébastien MB <seb@essembeh.org>"]
license = "Apache-2.0"
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Utilities"
]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.111.0"
beautifulsoup4 = "^4.12.2"
jinja2 = "^3.1.2"
arrow = "^1.2.3"
loguru = "^0.7.2"
environ-config = "^23.2.0"
redis = "^5.0.1"
httpx = "^0.27.0"
pydantic-yaml = "^1.3.0"
argon2-cffi = "^23.1.0"


[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-cov = "*"
pytest-dotenv = "*"
uvicorn = "*"
types-redis = "*"
pytest-asyncio = "*"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
