{{- if .Values.redis.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "yourss.fullname" . }}-redis
  labels:
    app: {{ template "yourss.fullname" . }}-redis
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "yourss.fullname" . }}-redis
  template:
    metadata:
      labels:
        app: {{ template "yourss.fullname" . }}-redis
    spec:
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ template "yourss.serviceAccountName" . }}
      {{- end }}
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 1000m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 32Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "yourss.fullname" . }}-redis
  labels:
    app: {{ template "yourss.fullname" . }}-redis
spec:
  type: ClusterIP
  selector:
    app: {{ template "yourss.fullname" . }}-redis
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: redis
{{- end }}
